---
abstract: 'Text::Xslate template engine for Dancer2'
author:
  - 'Richard Simões <rsimoes AT cpan DOT org>'
build_requires:
  Dancer2: '0'
  File::Spec: '0'
  HTTP::Request::Common: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Plack::Test: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Template-Xslate
requires:
  Moo: '0'
  Text::Xslate: '0'
  perl: v5.10.0
resources:
  bugtracker: https://github.com/rsimoes/dancer2-template-xslate/issues
  homepage: https://metacpan.org/release/Dancer2-Template-Xslate
  repository: git://github.com/rsimoes/dancer2-template-xslate.git
version: v0.0.7
